apiVersion: v1
kind: Service
metadata:
  name: k8s-page
  labels:
    app: k8s-page
spec:
  type: NodePort
  selector:
    app: k8s-page
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30081
